#!/bin/bash
# Create aliases for all command adaptors in this directory

adaptor_root=$1

for adaptor in $(ls $adaptor_root)
do
    adaptor_path=$adaptor_root/$adaptor/$adaptor
    
    if [ -f $adaptor_path ]; then
        echo "Loaded '$adaptor' adaptor" 
        alias $adaptor='$adaptor_path'
    elif [ -d $adaptor_root/$adaptor ]; then
        echo "Failed to load '$adaptor' adaptor, missing: $adaptor_path"
    fi
done
