#!/bin/bash
# Example of an enirely new sub-command

# Help
usage="commit-merge: Commit the files and directories in a path and merge those changes
to other checkouts and commit them there too. Be nice if this supported ranges too...

Valid options:
  -m            : message
  -c            : a changeset to use when merging instead of commiting
  -u            : update checkouts before commiting and merging
  
Example:
  svn commit-merge -m \"foo bar\" app/templates [../staging.last.fm[, ../i18.last.fm]]
"

if [ -z $1 ]; then
    echo "$usage" && exit 1
fi

# Options and arguments
while getopts ":m:c:u" opt; do
    case $opt in
            m ) message=$OPTARG ;;
            c ) changeset=$OPTARG ;;
            u ) update=true ;;
            h | \? ) echo "$usage" && exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

# Grab the path we're working with
path=$1 && shift

# Commit
if [ -z "$changeset" ]; then
    
    # Update the commit path first?
    if [ $update ]; then
        echo "svn update $path"
    fi
    
    # Commit, grab the output (This is messy, can it just be done once?)
    if [ -n "$message" ]; then
        commit=$(svn commit $path -m "$message")
    else
        commit=$(svn commit $path)
    fi
    
    echo $commit
    
    # Check last exit for failure and abort
    if [ $? -gt 0 ]; then
        exit $? # Let the svn error speak for itself
    fi

    # Extract the changeset (nicer way to do this?)
    changeset=$(echo $commit | sed -e 's/.* \([0-9]*\)*\.$/\1/') 
fi

echo $*

# Do merges
for checkout in $*
    do
    if [ $update ]; then
        echo "svn update $checkout/$path"
    fi
    
    name=$(basename $checkout | sed 's/.last.fm//')
    
    echo "Merging [$changeset] to $name"
    
    svn merge -c $changeset $path $checkout/$path
    svn ci -m "[$changeset] to $name -- $message" $checkout/$path
    
done