#!/bin/bash
# This allows you to adapt and extend commands,
# This example allows additonal or replacement sub-commends for svn

adaptor=${_%/*}/$1
command="svn"

# Check if an adapator exists and use that
if [ -f $adaptor ]; then
    command=$adaptor
    shift # Pop the sub-command
fi

# Call and pass the original arguments
$command "$@"