#!/bin/bash
# This allows you to adapt and extend commands, particularly those that 
# support sub-commands, such as; svn or git.

command="svn"
adaptor="/Users/user/command-adaptor/$command/$1" # $1 is the sub-command

# Check if an adapator exists and use that
if [ -f $adaptor ]; then
    command=$adaptor
    shift # Pop the sub-command name
fi

# Call and pass the original arguments
$command "$@"